### ISSUE TITLE
http 500 - pr0booru theme breaks after last upstream merge

### ISSUE THREAD

**Issue by Giraffaman** [Giraffaman/shimmie2#18]
after most recent merge from upstream, getting HTTP 500 when navigating to /post/list

Issue:
/var/log/unit.log in shimmie2 container:
`
2024/01/02 00:22:37 [info] 78#78 "shimmie" application started
2024/01/02 00:22:37 [notice] 68#68 [unit] #14: php message: PHP Fatal error:  Uncaught Error: Class "Shimmie2\ViewImageTheme" not found in /app/themes/pr0booru/view.theme.php:7
Stack trace:
#0 /app/core/util.php(555): require_once()
#1 /app/core/util.php(581): Shimmie2\require_all()
#2 /app/index.php(54): Shimmie2\_load_theme_files()
#3 {main}
  thrown in /app/themes/pr0booru/view.theme.php on line 7
`

Cause:
Upstream commit b67fca51f5f0f45cdcf4728f063caa20e0e1799a

Resolution:
need to update class references in pr0booru theme

**Comment by Giraffaman** [comment]
fixed in eb239fcdf9f281b597e82fca57a239b15dd949bb
