### ISSUE TITLE
http 500 - Danbooru-based themes - /system broken after last upstream merge

### ISSUE THREAD

**Issue by Giraffaman** [Giraffaman/shimmie2#20]
clicking on System results in HTTP 500 and unit log entry:
`
2024/01/02 11:55:34 [notice] 81#81 [unit] #131: php message: PHP Fatal error:  Uncaught TypeError: usort(): Argument #2 ($callback) must be a valid callback, function "Shimmie2\sort_nav_links" not found or invalid function name in /app/ext/system/main.php:15
Stack trace:
#0 /app/ext/system/main.php(15): usort()
#1 /app/core/send_event.php(156): Shimmie2\System->onPageRequest()
#2 /app/index.php(85): Shimmie2\send_event()
#3 {main}
  thrown in /app/ext/system/main.php on line 15
`

Cause:
f00a4e3 - see https://github.com/shish/shimmie2/issues/986

Workaround is to navigate to /setup for now.

**Comment by Giraffaman** [comment]
fixed upstream with 145deae
merged with e02edd87ebb66e1b472a67a3e5beeb23f633f42c
