### ISSUE TITLE
HTTP 500 when using redis or memcached 

### ISSUE THREAD

**Issue by Giraffaman** [Giraffaman/shimmie2#29]
with redis:
```
2024/01/07 17:19:55 [notice] 65#65 [unit] #13: php message: PHP Fatal error:  Uncaught Predis\Response\ServerException: ERR invalid expire time in 'setex' command in /app/vendor/predis/predis/src/Client.php:370
Stack trace:
#0 /app/vendor/predis/predis/src/Client.php(335): Predis\Client->onErrorResponse()
#1 /app/vendor/predis/predis/src/Client.php(313): Predis\Client->executeCommand()
#2 /app/vendor/naroga/redis-cache/Redis.php(79): Predis\Client->__call()
#3 /app/core/cacheengine.php(49): Naroga\RedisCache\Redis->set()
#4 /app/core/polyfills.php(806): Shimmie2\EventTracingCache->set()
#5 /app/core/config.php(282): Shimmie2\cache_get_or_set()
#6 /app/index.php(52): Shimmie2\DatabaseConfig->__construct()
#7 {main}
  thrown in /app/vendor/predis/predis/src/Client.php on line 370
```

with memcached:
```
2024/01/07 14:29:15 [notice] 63#63 [unit] #10: php message: PHP Fatal error:  Uncaught Error: Class "Memcached" not found in /app/core/cacheengine.php:110
Stack trace:
#0 /app/index.php(50): Shimmie2\loadCache()
#1 {main}
  thrown in /app/core/cacheengine.php on line 110
```

**Comment by Giraffaman** [comment]
fixed upstream with https://github.com/shish/shimmie2/issues/997
