### ISSUE TITLE
upstream merge bugs

### ISSUE THREAD

**Issue by Giraffaman** [Giraffaman/shimmie2#30]

**Comment by Giraffaman** [comment]
`2024/02/24 00:20:38 [notice] 27#27 [unit] #10: php message: PHP Fatal error:  Declaration of Shimmie2\Page::disable_left() must be compatible with Shimmie2\BasePage::disable_left(): void in /app/themes/pr0booru/page.class.php on line 55`

**Comment by Giraffaman** [comment]
`2024/02/24 00:37:46 [notice] 26#26 [unit] #10: php message: PHP Fatal error:  Declaration of Shimmie2\Themelet::display_paginator(Shimmie2\Page $page, string $base, ?string $query, int $page_number, int $total_pages, bool $show_random = false) must be compatible with Shimmie2\BaseThemelet::display_paginator(Shimmie2\Page $page, string $base, ?string $query, int $page_number, int $total_pages, bool $show_random = false): void in /app/themes/pr0booru/themelet.class.php on line 13`

**Comment by Giraffaman** [comment]
`2024/02/24 00:49:02 [notice] 26#26 [unit] #10: php message: PHP Fatal error:  Declaration of Shimmie2\CustomCommentListTheme::display_comment_list(array $images, int $page_number, int $total_pages, bool $can_post) must be compatible with Shimmie2\CommentListTheme::display_comment_list(array $images, int $page_number, int $total_pages, bool $can_post): void in /app/themes/pr0booru/comment.theme.php on line 9`

**Comment by Giraffaman** [comment]
on successful login:
```
2024/02/24 01:21:57 [notice] 38#38 [unit] #76: php message: PHP Fatal error:  Uncaught TypeError: Shimmie2\make_form(): Argument #2 ($multipart) must be of type bool, string given, called in /app/themes/pr0booru/page.class.php on line 162 and defined in /app/core/util.php:766
Stack trace:
#0 /app/themes/pr0booru/page.class.php(162): Shimmie2\make_form()
#1 /app/core/basepage.php(295): Shimmie2\Page->render()
#2 /app/index.php(92): Shimmie2\BasePage->display()
#3 {main}
  thrown in /app/core/util.php on line 766
```

**Comment by Giraffaman** [comment]
clicking apply on rating control form in navbar:
```
2024/02/24 01:40:31 [notice] 27#27 [unit] #18: php message: PHP Fatal error:  Uncaught Error: Call to undefined method Shimmie2\PageRequestEvent::count_args() in /app/ext/rating/main.php:403
Stack trace:
#0 /app/core/send_event.php(161): Shimmie2\Ratings->onPageRequest()
#1 /app/index.php(91): Shimmie2\send_event()
#2 {main}
  thrown in /app/ext/rating/main.php on line 403

```

**Comment by Giraffaman** [comment]
clicking on any image displayed in /post/list does not redirect to /post/view/n, but logs the following error:
```
2024/02/24 14:57:46 [notice] 35#35 [unit] #65: php message: PHP Warning:  Undefined property: Shimmie2\Image::$rating in /app/themes/pr0booru/view.theme.php on line 54
2024/02/24 14:57:46 [notice] 35#35 [unit] #65: php message: don't want to see this!

```

**Comment by Giraffaman** [comment]
related: calling /comment/list:
```
2024/02/24 15:40:01 [notice] 38#38 [unit] #79: php message: PHP Fatal error:  Uncaught TypeError: Shimmie2\Ratings::rating_to_human(): Argument #1 ($rating) must be of type string, null given, called in /app/themes/pr0booru/comment.theme.php on line 52 and defined in /app/ext/rating/main.php:559
Stack trace:
#0 /app/themes/pr0booru/comment.theme.php(52): Shimmie2\Ratings::rating_to_human()
#1 /app/ext/comment/main.php(283): Shimmie2\CustomCommentListTheme->display_comment_list()
#2 /app/core/send_event.php(161): Shimmie2\CommentList->onPageRequest()
#3 /app/index.php(91): Shimmie2\send_event()
#4 {main}
  thrown in /app/ext/rating/main.php on line 559

```

**Comment by Giraffaman** [comment]
related: clicking on rated/unrated image still won't load the image, logs:
`2024/02/24 15:55:06 [notice] 31#31 [unit] #36: php message: PHP Warning:  Undefined property: Shimmie2\Image::$rating in /app/ext/rating/main.php on line 114
`

**Comment by Giraffaman** [comment]
popular tags extension seems broken: 
- tag numbers are not refreshed
- new tags are not displayed in the list, but are present in /tags and are searchable

**Comment by Giraffaman** [comment]
some functions in /pool are available to anon users again (e.g. see changes to pools)

**Comment by Giraffaman** [comment]
popular tag numbers still broken:
- new tags are not added to the list, even if they should be popular because they include hundreds of images
- tags that don't contain (enough) images anymore are not removed
- all of the above is refreshed only when the entire stack stops and restarts (something with interacting with the db?)

**Comment by Giraffaman** [comment]
> popular tag numbers still broken:
> 
>     * new tags are not added to the list, even if they should be popular because they include hundreds of images
> 
>     * tags that don't contain (enough) images anymore are not removed
> 
>     * all of the above is refreshed only when the entire stack stops and restarts (something with interacting with the db?)

turns out this happens only when a cache is used. Cannot reproduce on a fresh install with no cache. Also explains why tag counts and list are refreshed when entire stack is stopped and started.

List entries and counts refresh about every 15mins.
