### ISSUE TITLE
permission denied when user/moderator presses apply on rating view control

### ISSUE THREAD

**Issue by Giraffaman** [Giraffaman/shimmie2#31]
users/mods can use Account > User Options > Default Rating Filter to set their desired default rating view, but pressing apply on the rating view control in the navbar causes the following error:
![image](https://github.com/Giraffaman/shimmie2/assets/56076467/b9b5f786-2f7c-4ce7-9c50-45f4feea9437)

**Comment by Giraffaman** [comment]
above screenshot is from prod env - in dev env, the same action causes an uncaught exception:
```
2024/02/25 00:09:35 [notice] 329#329 [unit] #130: php message: PHP Fatal error:  Uncaught Error: Class "Shimmie2\PermissionDeniedException" not found in /app/ext/rating/main.php:409
Stack trace:
#0 /app/core/send_event.php(161): Shimmie2\Ratings->onPageRequest()
#1 /app/index.php(91): Shimmie2\send_event()
#2 {main}
  thrown in /app/ext/rating/main.php on line 409

```
